/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as TreinarIaRouteImport } from './routes/treinar-ia'
import { Route as TestesRouteImport } from './routes/testes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SegurancaLocalRouteImport } from './routes/seguranca-local'
import { Route as SaasPlanosRouteImport } from './routes/saas-planos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RenovacoesPaineisRouteImport } from './routes/renovacoes-paineis'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as RegrasDisparoRouteImport } from './routes/regras-disparo'
import { Route as PreparacaoBackendRouteImport } from './routes/preparacao-backend'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as OperacaoDiaRouteImport } from './routes/operacao-dia'
import { Route as MinhaAssinaturaRouteImport } from './routes/minha-assinatura'
import { Route as MigracaoEmpresaRouteImport } from './routes/migracao-empresa'
import { Route as MeusDadosRouteImport } from './routes/meus-dados'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndicacoesRouteImport } from './routes/indicacoes'
import { Route as ImportarClientesRouteImport } from './routes/importar-clientes'
import { Route as IaConfigRouteImport } from './routes/ia-config'
import { Route as IaAtendenteRouteImport } from './routes/ia-atendente'
import { Route as IaRouteImport } from './routes/ia'
import { Route as GestaoServicosRouteImport } from './routes/gestao-servicos'
import { Route as FuncionalidadesRouteImport } from './routes/funcionalidades'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FilaSimuladaRouteImport } from './routes/fila-simulada'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ConfiguracoesRevendaRouteImport } from './routes/configuracoes-revenda'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConfiguracaoInicialRouteImport } from './routes/configuracao-inicial'
import { Route as CobrancasRouteImport } from './routes/cobrancas'
import { Route as CobrancaAutomaticaRouteImport } from './routes/cobranca-automatica'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CatalogoServidoresRouteImport } from './routes/catalogo-servidores'
import { Route as CampanhasManuaisRouteImport } from './routes/campanhas-manuais'
import { Route as CadastrosServicosRouteImport } from './routes/cadastros-servicos'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BaseConhecimentoRouteImport } from './routes/base-conhecimento'
import { Route as BackupGeralRouteImport } from './routes/backup-geral'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppsPortalRouteImport } from './routes/apps-portal'
import { Route as AjudaIaRouteImport } from './routes/ajuda-ia'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AgendaDisparoRouteImport } from './routes/agenda-disparo'
import { Route as AdminPlanosPagamentosRouteImport } from './routes/admin-planos-pagamentos'
import { Route as AdminDnsRotasRouteImport } from './routes/admin-dns-rotas'
import { Route as AcessoRestritoRouteImport } from './routes/acesso-restrito'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagarRefRouteImport } from './routes/pagar.$ref'
import { Route as PagamentosMercadoPagoRouteImport } from './routes/pagamentos.mercado-pago'
import { Route as PagamentosHistoricoRouteImport } from './routes/pagamentos.historico'
import { Route as AtendimentoIaTokenRouteImport } from './routes/atendimento-ia.$token'
import { Route as AdminVpsRouteImport } from './routes/admin.vps'
import { Route as AdminMarketplaceRouteImport } from './routes/admin.marketplace'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksMercadoPagoRouteImport } from './routes/api/public/webhooks/mercado-pago'
import { Route as ApiPublicWebhooksEvolutionRouteImport } from './routes/api/public/webhooks/evolution'
import { Route as ApiPublicMpSaasWebhookRouteImport } from './routes/api/public/mp/saas-webhook'
import { Route as ApiPublicMpOauthCallbackRouteImport } from './routes/api/public/mp/oauth-callback'
import { Route as ApiPublicMpMarketplaceWebhookRouteImport } from './routes/api/public/mp/marketplace-webhook'
import { Route as ApiPublicHooksWaDispatchRouteImport } from './routes/api/public/hooks/wa-dispatch'
import { Route as ApiPublicHooksSyncCronSecretRouteImport } from './routes/api/public/hooks/sync-cron-secret'
import { Route as ApiPublicHooksServicesDispatchRouteImport } from './routes/api/public/hooks/services-dispatch'
import { Route as ApiPublicWebhooksEvolutionInstanceRouteImport } from './routes/api/public/webhooks/evolution.$instance'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinarIaRoute = TreinarIaRouteImport.update({
  id: '/treinar-ia',
  path: '/treinar-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const TestesRoute = TestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaLocalRoute = SegurancaLocalRouteImport.update({
  id: '/seguranca-local',
  path: '/seguranca-local',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasPlanosRoute = SaasPlanosRouteImport.update({
  id: '/saas-planos',
  path: '/saas-planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovacoesPaineisRoute = RenovacoesPaineisRouteImport.update({
  id: '/renovacoes-paineis',
  path: '/renovacoes-paineis',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasDisparoRoute = RegrasDisparoRouteImport.update({
  id: '/regras-disparo',
  path: '/regras-disparo',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparacaoBackendRoute = PreparacaoBackendRouteImport.update({
  id: '/preparacao-backend',
  path: '/preparacao-backend',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoDiaRoute = OperacaoDiaRouteImport.update({
  id: '/operacao-dia',
  path: '/operacao-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAssinaturaRoute = MinhaAssinaturaRouteImport.update({
  id: '/minha-assinatura',
  path: '/minha-assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const MigracaoEmpresaRoute = MigracaoEmpresaRouteImport.update({
  id: '/migracao-empresa',
  path: '/migracao-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusDadosRoute = MeusDadosRouteImport.update({
  id: '/meus-dados',
  path: '/meus-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacoesRoute = IndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarClientesRoute = ImportarClientesRouteImport.update({
  id: '/importar-clientes',
  path: '/importar-clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IaConfigRoute = IaConfigRouteImport.update({
  id: '/ia-config',
  path: '/ia-config',
  getParentRoute: () => rootRouteImport,
} as any)
const IaAtendenteRoute = IaAtendenteRouteImport.update({
  id: '/ia-atendente',
  path: '/ia-atendente',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoServicosRoute = GestaoServicosRouteImport.update({
  id: '/gestao-servicos',
  path: '/gestao-servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionalidadesRoute = FuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaSimuladaRoute = FilaSimuladaRouteImport.update({
  id: '/fila-simulada',
  path: '/fila-simulada',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRevendaRoute = ConfiguracoesRevendaRouteImport.update({
  id: '/configuracoes-revenda',
  path: '/configuracoes-revenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracaoInicialRoute = ConfiguracaoInicialRouteImport.update({
  id: '/configuracao-inicial',
  path: '/configuracao-inicial',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancasRoute = CobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaAutomaticaRoute = CobrancaAutomaticaRouteImport.update({
  id: '/cobranca-automatica',
  path: '/cobranca-automatica',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoServidoresRoute = CatalogoServidoresRouteImport.update({
  id: '/catalogo-servidores',
  path: '/catalogo-servidores',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasManuaisRoute = CampanhasManuaisRouteImport.update({
  id: '/campanhas-manuais',
  path: '/campanhas-manuais',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosServicosRoute = CadastrosServicosRouteImport.update({
  id: '/cadastros-servicos',
  path: '/cadastros-servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseConhecimentoRoute = BaseConhecimentoRouteImport.update({
  id: '/base-conhecimento',
  path: '/base-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupGeralRoute = BackupGeralRouteImport.update({
  id: '/backup-geral',
  path: '/backup-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPortalRoute = AppsPortalRouteImport.update({
  id: '/apps-portal',
  path: '/apps-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaIaRoute = AjudaIaRouteImport.update({
  id: '/ajuda-ia',
  path: '/ajuda-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaDisparoRoute = AgendaDisparoRouteImport.update({
  id: '/agenda-disparo',
  path: '/agenda-disparo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlanosPagamentosRoute = AdminPlanosPagamentosRouteImport.update({
  id: '/admin-planos-pagamentos',
  path: '/admin-planos-pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDnsRotasRoute = AdminDnsRotasRouteImport.update({
  id: '/admin-dns-rotas',
  path: '/admin-dns-rotas',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRestritoRoute = AcessoRestritoRouteImport.update({
  id: '/acesso-restrito',
  path: '/acesso-restrito',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarRefRoute = PagarRefRouteImport.update({
  id: '/pagar/$ref',
  path: '/pagar/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosMercadoPagoRoute = PagamentosMercadoPagoRouteImport.update({
  id: '/pagamentos/mercado-pago',
  path: '/pagamentos/mercado-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosHistoricoRoute = PagamentosHistoricoRouteImport.update({
  id: '/pagamentos/historico',
  path: '/pagamentos/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoIaTokenRoute = AtendimentoIaTokenRouteImport.update({
  id: '/atendimento-ia/$token',
  path: '/atendimento-ia/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVpsRoute = AdminVpsRouteImport.update({
  id: '/admin/vps',
  path: '/admin/vps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/admin/marketplace',
  path: '/admin/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadoPagoRoute =
  ApiPublicWebhooksMercadoPagoRouteImport.update({
    id: '/api/public/webhooks/mercado-pago',
    path: '/api/public/webhooks/mercado-pago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksEvolutionRoute =
  ApiPublicWebhooksEvolutionRouteImport.update({
    id: '/api/public/webhooks/evolution',
    path: '/api/public/webhooks/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpSaasWebhookRoute = ApiPublicMpSaasWebhookRouteImport.update({
  id: '/api/public/mp/saas-webhook',
  path: '/api/public/mp/saas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpOauthCallbackRoute =
  ApiPublicMpOauthCallbackRouteImport.update({
    id: '/api/public/mp/oauth-callback',
    path: '/api/public/mp/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpMarketplaceWebhookRoute =
  ApiPublicMpMarketplaceWebhookRouteImport.update({
    id: '/api/public/mp/marketplace-webhook',
    path: '/api/public/mp/marketplace-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWaDispatchRoute =
  ApiPublicHooksWaDispatchRouteImport.update({
    id: '/api/public/hooks/wa-dispatch',
    path: '/api/public/hooks/wa-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncCronSecretRoute =
  ApiPublicHooksSyncCronSecretRouteImport.update({
    id: '/api/public/hooks/sync-cron-secret',
    path: '/api/public/hooks/sync-cron-secret',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksServicesDispatchRoute =
  ApiPublicHooksServicesDispatchRouteImport.update({
    id: '/api/public/hooks/services-dispatch',
    path: '/api/public/hooks/services-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksEvolutionInstanceRoute =
  ApiPublicWebhooksEvolutionInstanceRouteImport.update({
    id: '/$instance',
    path: '/$instance',
    getParentRoute: () => ApiPublicWebhooksEvolutionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-restrito': typeof AcessoRestritoRoute
  '/admin-dns-rotas': typeof AdminDnsRotasRoute
  '/admin-planos-pagamentos': typeof AdminPlanosPagamentosRoute
  '/agenda-disparo': typeof AgendaDisparoRoute
  '/ajuda': typeof AjudaRoute
  '/ajuda-ia': typeof AjudaIaRoute
  '/apps-portal': typeof AppsPortalRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/backup-geral': typeof BackupGeralRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/blog': typeof BlogRoute
  '/cadastros-servicos': typeof CadastrosServicosRoute
  '/campanhas-manuais': typeof CampanhasManuaisRoute
  '/catalogo-servidores': typeof CatalogoServidoresRoute
  '/clientes': typeof ClientesRoute
  '/cobranca-automatica': typeof CobrancaAutomaticaRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracao-inicial': typeof ConfiguracaoInicialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/configuracoes-revenda': typeof ConfiguracoesRevendaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/empresas': typeof EmpresasRoute
  '/faq': typeof FaqRoute
  '/fila-simulada': typeof FilaSimuladaRoute
  '/financeiro': typeof FinanceiroRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/gestao-servicos': typeof GestaoServicosRoute
  '/ia': typeof IaRoute
  '/ia-atendente': typeof IaAtendenteRoute
  '/ia-config': typeof IaConfigRoute
  '/importar-clientes': typeof ImportarClientesRoute
  '/indicacoes': typeof IndicacoesRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/meus-dados': typeof MeusDadosRoute
  '/migracao-empresa': typeof MigracaoEmpresaRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/operacao-dia': typeof OperacaoDiaRoute
  '/pendencias': typeof PendenciasRoute
  '/planos': typeof PlanosRoute
  '/preparacao-backend': typeof PreparacaoBackendRoute
  '/regras-disparo': typeof RegrasDisparoRoute
  '/relatorio': typeof RelatorioRoute
  '/renovacoes-paineis': typeof RenovacoesPaineisRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas-planos': typeof SaasPlanosRoute
  '/seguranca-local': typeof SegurancaLocalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testes': typeof TestesRoute
  '/treinar-ia': typeof TreinarIaRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/vps': typeof AdminVpsRoute
  '/atendimento-ia/$token': typeof AtendimentoIaTokenRoute
  '/pagamentos/historico': typeof PagamentosHistoricoRoute
  '/pagamentos/mercado-pago': typeof PagamentosMercadoPagoRoute
  '/pagar/$ref': typeof PagarRefRoute
  '/api/public/hooks/services-dispatch': typeof ApiPublicHooksServicesDispatchRoute
  '/api/public/hooks/sync-cron-secret': typeof ApiPublicHooksSyncCronSecretRoute
  '/api/public/hooks/wa-dispatch': typeof ApiPublicHooksWaDispatchRoute
  '/api/public/mp/marketplace-webhook': typeof ApiPublicMpMarketplaceWebhookRoute
  '/api/public/mp/oauth-callback': typeof ApiPublicMpOauthCallbackRoute
  '/api/public/mp/saas-webhook': typeof ApiPublicMpSaasWebhookRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRouteWithChildren
  '/api/public/webhooks/mercado-pago': typeof ApiPublicWebhooksMercadoPagoRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/webhooks/evolution/$instance': typeof ApiPublicWebhooksEvolutionInstanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-restrito': typeof AcessoRestritoRoute
  '/admin-dns-rotas': typeof AdminDnsRotasRoute
  '/admin-planos-pagamentos': typeof AdminPlanosPagamentosRoute
  '/agenda-disparo': typeof AgendaDisparoRoute
  '/ajuda': typeof AjudaRoute
  '/ajuda-ia': typeof AjudaIaRoute
  '/apps-portal': typeof AppsPortalRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/backup-geral': typeof BackupGeralRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/blog': typeof BlogRoute
  '/cadastros-servicos': typeof CadastrosServicosRoute
  '/campanhas-manuais': typeof CampanhasManuaisRoute
  '/catalogo-servidores': typeof CatalogoServidoresRoute
  '/clientes': typeof ClientesRoute
  '/cobranca-automatica': typeof CobrancaAutomaticaRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracao-inicial': typeof ConfiguracaoInicialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/configuracoes-revenda': typeof ConfiguracoesRevendaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/empresas': typeof EmpresasRoute
  '/faq': typeof FaqRoute
  '/fila-simulada': typeof FilaSimuladaRoute
  '/financeiro': typeof FinanceiroRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/gestao-servicos': typeof GestaoServicosRoute
  '/ia': typeof IaRoute
  '/ia-atendente': typeof IaAtendenteRoute
  '/ia-config': typeof IaConfigRoute
  '/importar-clientes': typeof ImportarClientesRoute
  '/indicacoes': typeof IndicacoesRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/meus-dados': typeof MeusDadosRoute
  '/migracao-empresa': typeof MigracaoEmpresaRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/operacao-dia': typeof OperacaoDiaRoute
  '/pendencias': typeof PendenciasRoute
  '/planos': typeof PlanosRoute
  '/preparacao-backend': typeof PreparacaoBackendRoute
  '/regras-disparo': typeof RegrasDisparoRoute
  '/relatorio': typeof RelatorioRoute
  '/renovacoes-paineis': typeof RenovacoesPaineisRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas-planos': typeof SaasPlanosRoute
  '/seguranca-local': typeof SegurancaLocalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testes': typeof TestesRoute
  '/treinar-ia': typeof TreinarIaRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/vps': typeof AdminVpsRoute
  '/atendimento-ia/$token': typeof AtendimentoIaTokenRoute
  '/pagamentos/historico': typeof PagamentosHistoricoRoute
  '/pagamentos/mercado-pago': typeof PagamentosMercadoPagoRoute
  '/pagar/$ref': typeof PagarRefRoute
  '/api/public/hooks/services-dispatch': typeof ApiPublicHooksServicesDispatchRoute
  '/api/public/hooks/sync-cron-secret': typeof ApiPublicHooksSyncCronSecretRoute
  '/api/public/hooks/wa-dispatch': typeof ApiPublicHooksWaDispatchRoute
  '/api/public/mp/marketplace-webhook': typeof ApiPublicMpMarketplaceWebhookRoute
  '/api/public/mp/oauth-callback': typeof ApiPublicMpOauthCallbackRoute
  '/api/public/mp/saas-webhook': typeof ApiPublicMpSaasWebhookRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRouteWithChildren
  '/api/public/webhooks/mercado-pago': typeof ApiPublicWebhooksMercadoPagoRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/webhooks/evolution/$instance': typeof ApiPublicWebhooksEvolutionInstanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-restrito': typeof AcessoRestritoRoute
  '/admin-dns-rotas': typeof AdminDnsRotasRoute
  '/admin-planos-pagamentos': typeof AdminPlanosPagamentosRoute
  '/agenda-disparo': typeof AgendaDisparoRoute
  '/ajuda': typeof AjudaRoute
  '/ajuda-ia': typeof AjudaIaRoute
  '/apps-portal': typeof AppsPortalRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/backup-geral': typeof BackupGeralRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/blog': typeof BlogRoute
  '/cadastros-servicos': typeof CadastrosServicosRoute
  '/campanhas-manuais': typeof CampanhasManuaisRoute
  '/catalogo-servidores': typeof CatalogoServidoresRoute
  '/clientes': typeof ClientesRoute
  '/cobranca-automatica': typeof CobrancaAutomaticaRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracao-inicial': typeof ConfiguracaoInicialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/configuracoes-revenda': typeof ConfiguracoesRevendaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/empresas': typeof EmpresasRoute
  '/faq': typeof FaqRoute
  '/fila-simulada': typeof FilaSimuladaRoute
  '/financeiro': typeof FinanceiroRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/gestao-servicos': typeof GestaoServicosRoute
  '/ia': typeof IaRoute
  '/ia-atendente': typeof IaAtendenteRoute
  '/ia-config': typeof IaConfigRoute
  '/importar-clientes': typeof ImportarClientesRoute
  '/indicacoes': typeof IndicacoesRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/meus-dados': typeof MeusDadosRoute
  '/migracao-empresa': typeof MigracaoEmpresaRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/operacao-dia': typeof OperacaoDiaRoute
  '/pendencias': typeof PendenciasRoute
  '/planos': typeof PlanosRoute
  '/preparacao-backend': typeof PreparacaoBackendRoute
  '/regras-disparo': typeof RegrasDisparoRoute
  '/relatorio': typeof RelatorioRoute
  '/renovacoes-paineis': typeof RenovacoesPaineisRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas-planos': typeof SaasPlanosRoute
  '/seguranca-local': typeof SegurancaLocalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testes': typeof TestesRoute
  '/treinar-ia': typeof TreinarIaRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/vps': typeof AdminVpsRoute
  '/atendimento-ia/$token': typeof AtendimentoIaTokenRoute
  '/pagamentos/historico': typeof PagamentosHistoricoRoute
  '/pagamentos/mercado-pago': typeof PagamentosMercadoPagoRoute
  '/pagar/$ref': typeof PagarRefRoute
  '/api/public/hooks/services-dispatch': typeof ApiPublicHooksServicesDispatchRoute
  '/api/public/hooks/sync-cron-secret': typeof ApiPublicHooksSyncCronSecretRoute
  '/api/public/hooks/wa-dispatch': typeof ApiPublicHooksWaDispatchRoute
  '/api/public/mp/marketplace-webhook': typeof ApiPublicMpMarketplaceWebhookRoute
  '/api/public/mp/oauth-callback': typeof ApiPublicMpOauthCallbackRoute
  '/api/public/mp/saas-webhook': typeof ApiPublicMpSaasWebhookRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRouteWithChildren
  '/api/public/webhooks/mercado-pago': typeof ApiPublicWebhooksMercadoPagoRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/webhooks/evolution/$instance': typeof ApiPublicWebhooksEvolutionInstanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-restrito'
    | '/admin-dns-rotas'
    | '/admin-planos-pagamentos'
    | '/agenda-disparo'
    | '/ajuda'
    | '/ajuda-ia'
    | '/apps-portal'
    | '/auth'
    | '/backup'
    | '/backup-geral'
    | '/base-conhecimento'
    | '/blog'
    | '/cadastros-servicos'
    | '/campanhas-manuais'
    | '/catalogo-servidores'
    | '/clientes'
    | '/cobranca-automatica'
    | '/cobrancas'
    | '/configuracao-inicial'
    | '/configuracoes'
    | '/configuracoes-revenda'
    | '/diagnostico'
    | '/empresas'
    | '/faq'
    | '/fila-simulada'
    | '/financeiro'
    | '/funcionalidades'
    | '/gestao-servicos'
    | '/ia'
    | '/ia-atendente'
    | '/ia-config'
    | '/importar-clientes'
    | '/indicacoes'
    | '/login'
    | '/mensagens'
    | '/meus-dados'
    | '/migracao-empresa'
    | '/minha-assinatura'
    | '/operacao-dia'
    | '/pendencias'
    | '/planos'
    | '/preparacao-backend'
    | '/regras-disparo'
    | '/relatorio'
    | '/renovacoes-paineis'
    | '/reset-password'
    | '/saas-planos'
    | '/seguranca-local'
    | '/sitemap.xml'
    | '/testes'
    | '/treinar-ia'
    | '/whatsapp'
    | '/admin/marketplace'
    | '/admin/vps'
    | '/atendimento-ia/$token'
    | '/pagamentos/historico'
    | '/pagamentos/mercado-pago'
    | '/pagar/$ref'
    | '/api/public/hooks/services-dispatch'
    | '/api/public/hooks/sync-cron-secret'
    | '/api/public/hooks/wa-dispatch'
    | '/api/public/mp/marketplace-webhook'
    | '/api/public/mp/oauth-callback'
    | '/api/public/mp/saas-webhook'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/mercado-pago'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/webhooks/evolution/$instance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-restrito'
    | '/admin-dns-rotas'
    | '/admin-planos-pagamentos'
    | '/agenda-disparo'
    | '/ajuda'
    | '/ajuda-ia'
    | '/apps-portal'
    | '/auth'
    | '/backup'
    | '/backup-geral'
    | '/base-conhecimento'
    | '/blog'
    | '/cadastros-servicos'
    | '/campanhas-manuais'
    | '/catalogo-servidores'
    | '/clientes'
    | '/cobranca-automatica'
    | '/cobrancas'
    | '/configuracao-inicial'
    | '/configuracoes'
    | '/configuracoes-revenda'
    | '/diagnostico'
    | '/empresas'
    | '/faq'
    | '/fila-simulada'
    | '/financeiro'
    | '/funcionalidades'
    | '/gestao-servicos'
    | '/ia'
    | '/ia-atendente'
    | '/ia-config'
    | '/importar-clientes'
    | '/indicacoes'
    | '/login'
    | '/mensagens'
    | '/meus-dados'
    | '/migracao-empresa'
    | '/minha-assinatura'
    | '/operacao-dia'
    | '/pendencias'
    | '/planos'
    | '/preparacao-backend'
    | '/regras-disparo'
    | '/relatorio'
    | '/renovacoes-paineis'
    | '/reset-password'
    | '/saas-planos'
    | '/seguranca-local'
    | '/sitemap.xml'
    | '/testes'
    | '/treinar-ia'
    | '/whatsapp'
    | '/admin/marketplace'
    | '/admin/vps'
    | '/atendimento-ia/$token'
    | '/pagamentos/historico'
    | '/pagamentos/mercado-pago'
    | '/pagar/$ref'
    | '/api/public/hooks/services-dispatch'
    | '/api/public/hooks/sync-cron-secret'
    | '/api/public/hooks/wa-dispatch'
    | '/api/public/mp/marketplace-webhook'
    | '/api/public/mp/oauth-callback'
    | '/api/public/mp/saas-webhook'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/mercado-pago'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/webhooks/evolution/$instance'
  id:
    | '__root__'
    | '/'
    | '/acesso-restrito'
    | '/admin-dns-rotas'
    | '/admin-planos-pagamentos'
    | '/agenda-disparo'
    | '/ajuda'
    | '/ajuda-ia'
    | '/apps-portal'
    | '/auth'
    | '/backup'
    | '/backup-geral'
    | '/base-conhecimento'
    | '/blog'
    | '/cadastros-servicos'
    | '/campanhas-manuais'
    | '/catalogo-servidores'
    | '/clientes'
    | '/cobranca-automatica'
    | '/cobrancas'
    | '/configuracao-inicial'
    | '/configuracoes'
    | '/configuracoes-revenda'
    | '/diagnostico'
    | '/empresas'
    | '/faq'
    | '/fila-simulada'
    | '/financeiro'
    | '/funcionalidades'
    | '/gestao-servicos'
    | '/ia'
    | '/ia-atendente'
    | '/ia-config'
    | '/importar-clientes'
    | '/indicacoes'
    | '/login'
    | '/mensagens'
    | '/meus-dados'
    | '/migracao-empresa'
    | '/minha-assinatura'
    | '/operacao-dia'
    | '/pendencias'
    | '/planos'
    | '/preparacao-backend'
    | '/regras-disparo'
    | '/relatorio'
    | '/renovacoes-paineis'
    | '/reset-password'
    | '/saas-planos'
    | '/seguranca-local'
    | '/sitemap.xml'
    | '/testes'
    | '/treinar-ia'
    | '/whatsapp'
    | '/admin/marketplace'
    | '/admin/vps'
    | '/atendimento-ia/$token'
    | '/pagamentos/historico'
    | '/pagamentos/mercado-pago'
    | '/pagar/$ref'
    | '/api/public/hooks/services-dispatch'
    | '/api/public/hooks/sync-cron-secret'
    | '/api/public/hooks/wa-dispatch'
    | '/api/public/mp/marketplace-webhook'
    | '/api/public/mp/oauth-callback'
    | '/api/public/mp/saas-webhook'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/mercado-pago'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/webhooks/evolution/$instance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoRestritoRoute: typeof AcessoRestritoRoute
  AdminDnsRotasRoute: typeof AdminDnsRotasRoute
  AdminPlanosPagamentosRoute: typeof AdminPlanosPagamentosRoute
  AgendaDisparoRoute: typeof AgendaDisparoRoute
  AjudaRoute: typeof AjudaRoute
  AjudaIaRoute: typeof AjudaIaRoute
  AppsPortalRoute: typeof AppsPortalRoute
  AuthRoute: typeof AuthRoute
  BackupRoute: typeof BackupRoute
  BackupGeralRoute: typeof BackupGeralRoute
  BaseConhecimentoRoute: typeof BaseConhecimentoRoute
  BlogRoute: typeof BlogRoute
  CadastrosServicosRoute: typeof CadastrosServicosRoute
  CampanhasManuaisRoute: typeof CampanhasManuaisRoute
  CatalogoServidoresRoute: typeof CatalogoServidoresRoute
  ClientesRoute: typeof ClientesRoute
  CobrancaAutomaticaRoute: typeof CobrancaAutomaticaRoute
  CobrancasRoute: typeof CobrancasRoute
  ConfiguracaoInicialRoute: typeof ConfiguracaoInicialRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConfiguracoesRevendaRoute: typeof ConfiguracoesRevendaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EmpresasRoute: typeof EmpresasRoute
  FaqRoute: typeof FaqRoute
  FilaSimuladaRoute: typeof FilaSimuladaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FuncionalidadesRoute: typeof FuncionalidadesRoute
  GestaoServicosRoute: typeof GestaoServicosRoute
  IaRoute: typeof IaRoute
  IaAtendenteRoute: typeof IaAtendenteRoute
  IaConfigRoute: typeof IaConfigRoute
  ImportarClientesRoute: typeof ImportarClientesRoute
  IndicacoesRoute: typeof IndicacoesRoute
  LoginRoute: typeof LoginRoute
  MensagensRoute: typeof MensagensRoute
  MeusDadosRoute: typeof MeusDadosRoute
  MigracaoEmpresaRoute: typeof MigracaoEmpresaRoute
  MinhaAssinaturaRoute: typeof MinhaAssinaturaRoute
  OperacaoDiaRoute: typeof OperacaoDiaRoute
  PendenciasRoute: typeof PendenciasRoute
  PlanosRoute: typeof PlanosRoute
  PreparacaoBackendRoute: typeof PreparacaoBackendRoute
  RegrasDisparoRoute: typeof RegrasDisparoRoute
  RelatorioRoute: typeof RelatorioRoute
  RenovacoesPaineisRoute: typeof RenovacoesPaineisRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaasPlanosRoute: typeof SaasPlanosRoute
  SegurancaLocalRoute: typeof SegurancaLocalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestesRoute: typeof TestesRoute
  TreinarIaRoute: typeof TreinarIaRoute
  WhatsappRoute: typeof WhatsappRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminVpsRoute: typeof AdminVpsRoute
  AtendimentoIaTokenRoute: typeof AtendimentoIaTokenRoute
  PagamentosHistoricoRoute: typeof PagamentosHistoricoRoute
  PagamentosMercadoPagoRoute: typeof PagamentosMercadoPagoRoute
  PagarRefRoute: typeof PagarRefRoute
  ApiPublicHooksServicesDispatchRoute: typeof ApiPublicHooksServicesDispatchRoute
  ApiPublicHooksSyncCronSecretRoute: typeof ApiPublicHooksSyncCronSecretRoute
  ApiPublicHooksWaDispatchRoute: typeof ApiPublicHooksWaDispatchRoute
  ApiPublicMpMarketplaceWebhookRoute: typeof ApiPublicMpMarketplaceWebhookRoute
  ApiPublicMpOauthCallbackRoute: typeof ApiPublicMpOauthCallbackRoute
  ApiPublicMpSaasWebhookRoute: typeof ApiPublicMpSaasWebhookRoute
  ApiPublicWebhooksEvolutionRoute: typeof ApiPublicWebhooksEvolutionRouteWithChildren
  ApiPublicWebhooksMercadoPagoRoute: typeof ApiPublicWebhooksMercadoPagoRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinar-ia': {
      id: '/treinar-ia'
      path: '/treinar-ia'
      fullPath: '/treinar-ia'
      preLoaderRoute: typeof TreinarIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testes': {
      id: '/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof TestesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca-local': {
      id: '/seguranca-local'
      path: '/seguranca-local'
      fullPath: '/seguranca-local'
      preLoaderRoute: typeof SegurancaLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas-planos': {
      id: '/saas-planos'
      path: '/saas-planos'
      fullPath: '/saas-planos'
      preLoaderRoute: typeof SaasPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovacoes-paineis': {
      id: '/renovacoes-paineis'
      path: '/renovacoes-paineis'
      fullPath: '/renovacoes-paineis'
      preLoaderRoute: typeof RenovacoesPaineisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras-disparo': {
      id: '/regras-disparo'
      path: '/regras-disparo'
      fullPath: '/regras-disparo'
      preLoaderRoute: typeof RegrasDisparoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparacao-backend': {
      id: '/preparacao-backend'
      path: '/preparacao-backend'
      fullPath: '/preparacao-backend'
      preLoaderRoute: typeof PreparacaoBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao-dia': {
      id: '/operacao-dia'
      path: '/operacao-dia'
      fullPath: '/operacao-dia'
      preLoaderRoute: typeof OperacaoDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-assinatura': {
      id: '/minha-assinatura'
      path: '/minha-assinatura'
      fullPath: '/minha-assinatura'
      preLoaderRoute: typeof MinhaAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migracao-empresa': {
      id: '/migracao-empresa'
      path: '/migracao-empresa'
      fullPath: '/migracao-empresa'
      preLoaderRoute: typeof MigracaoEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-dados': {
      id: '/meus-dados'
      path: '/meus-dados'
      fullPath: '/meus-dados'
      preLoaderRoute: typeof MeusDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacoes': {
      id: '/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof IndicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-clientes': {
      id: '/importar-clientes'
      path: '/importar-clientes'
      fullPath: '/importar-clientes'
      preLoaderRoute: typeof ImportarClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-config': {
      id: '/ia-config'
      path: '/ia-config'
      fullPath: '/ia-config'
      preLoaderRoute: typeof IaConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-atendente': {
      id: '/ia-atendente'
      path: '/ia-atendente'
      fullPath: '/ia-atendente'
      preLoaderRoute: typeof IaAtendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-servicos': {
      id: '/gestao-servicos'
      path: '/gestao-servicos'
      fullPath: '/gestao-servicos'
      preLoaderRoute: typeof GestaoServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades': {
      id: '/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/funcionalidades'
      preLoaderRoute: typeof FuncionalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila-simulada': {
      id: '/fila-simulada'
      path: '/fila-simulada'
      fullPath: '/fila-simulada'
      preLoaderRoute: typeof FilaSimuladaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-revenda': {
      id: '/configuracoes-revenda'
      path: '/configuracoes-revenda'
      fullPath: '/configuracoes-revenda'
      preLoaderRoute: typeof ConfiguracoesRevendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracao-inicial': {
      id: '/configuracao-inicial'
      path: '/configuracao-inicial'
      fullPath: '/configuracao-inicial'
      preLoaderRoute: typeof ConfiguracaoInicialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobrancas': {
      id: '/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof CobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca-automatica': {
      id: '/cobranca-automatica'
      path: '/cobranca-automatica'
      fullPath: '/cobranca-automatica'
      preLoaderRoute: typeof CobrancaAutomaticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo-servidores': {
      id: '/catalogo-servidores'
      path: '/catalogo-servidores'
      fullPath: '/catalogo-servidores'
      preLoaderRoute: typeof CatalogoServidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas-manuais': {
      id: '/campanhas-manuais'
      path: '/campanhas-manuais'
      fullPath: '/campanhas-manuais'
      preLoaderRoute: typeof CampanhasManuaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros-servicos': {
      id: '/cadastros-servicos'
      path: '/cadastros-servicos'
      fullPath: '/cadastros-servicos'
      preLoaderRoute: typeof CadastrosServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-conhecimento': {
      id: '/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof BaseConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup-geral': {
      id: '/backup-geral'
      path: '/backup-geral'
      fullPath: '/backup-geral'
      preLoaderRoute: typeof BackupGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps-portal': {
      id: '/apps-portal'
      path: '/apps-portal'
      fullPath: '/apps-portal'
      preLoaderRoute: typeof AppsPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda-ia': {
      id: '/ajuda-ia'
      path: '/ajuda-ia'
      fullPath: '/ajuda-ia'
      preLoaderRoute: typeof AjudaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-disparo': {
      id: '/agenda-disparo'
      path: '/agenda-disparo'
      fullPath: '/agenda-disparo'
      preLoaderRoute: typeof AgendaDisparoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-planos-pagamentos': {
      id: '/admin-planos-pagamentos'
      path: '/admin-planos-pagamentos'
      fullPath: '/admin-planos-pagamentos'
      preLoaderRoute: typeof AdminPlanosPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dns-rotas': {
      id: '/admin-dns-rotas'
      path: '/admin-dns-rotas'
      fullPath: '/admin-dns-rotas'
      preLoaderRoute: typeof AdminDnsRotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-restrito': {
      id: '/acesso-restrito'
      path: '/acesso-restrito'
      fullPath: '/acesso-restrito'
      preLoaderRoute: typeof AcessoRestritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagar/$ref': {
      id: '/pagar/$ref'
      path: '/pagar/$ref'
      fullPath: '/pagar/$ref'
      preLoaderRoute: typeof PagarRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos/mercado-pago': {
      id: '/pagamentos/mercado-pago'
      path: '/pagamentos/mercado-pago'
      fullPath: '/pagamentos/mercado-pago'
      preLoaderRoute: typeof PagamentosMercadoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos/historico': {
      id: '/pagamentos/historico'
      path: '/pagamentos/historico'
      fullPath: '/pagamentos/historico'
      preLoaderRoute: typeof PagamentosHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento-ia/$token': {
      id: '/atendimento-ia/$token'
      path: '/atendimento-ia/$token'
      fullPath: '/atendimento-ia/$token'
      preLoaderRoute: typeof AtendimentoIaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vps': {
      id: '/admin/vps'
      path: '/admin/vps'
      fullPath: '/admin/vps'
      preLoaderRoute: typeof AdminVpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/admin/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercado-pago': {
      id: '/api/public/webhooks/mercado-pago'
      path: '/api/public/webhooks/mercado-pago'
      fullPath: '/api/public/webhooks/mercado-pago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/evolution': {
      id: '/api/public/webhooks/evolution'
      path: '/api/public/webhooks/evolution'
      fullPath: '/api/public/webhooks/evolution'
      preLoaderRoute: typeof ApiPublicWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/saas-webhook': {
      id: '/api/public/mp/saas-webhook'
      path: '/api/public/mp/saas-webhook'
      fullPath: '/api/public/mp/saas-webhook'
      preLoaderRoute: typeof ApiPublicMpSaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/oauth-callback': {
      id: '/api/public/mp/oauth-callback'
      path: '/api/public/mp/oauth-callback'
      fullPath: '/api/public/mp/oauth-callback'
      preLoaderRoute: typeof ApiPublicMpOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/marketplace-webhook': {
      id: '/api/public/mp/marketplace-webhook'
      path: '/api/public/mp/marketplace-webhook'
      fullPath: '/api/public/mp/marketplace-webhook'
      preLoaderRoute: typeof ApiPublicMpMarketplaceWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wa-dispatch': {
      id: '/api/public/hooks/wa-dispatch'
      path: '/api/public/hooks/wa-dispatch'
      fullPath: '/api/public/hooks/wa-dispatch'
      preLoaderRoute: typeof ApiPublicHooksWaDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-cron-secret': {
      id: '/api/public/hooks/sync-cron-secret'
      path: '/api/public/hooks/sync-cron-secret'
      fullPath: '/api/public/hooks/sync-cron-secret'
      preLoaderRoute: typeof ApiPublicHooksSyncCronSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/services-dispatch': {
      id: '/api/public/hooks/services-dispatch'
      path: '/api/public/hooks/services-dispatch'
      fullPath: '/api/public/hooks/services-dispatch'
      preLoaderRoute: typeof ApiPublicHooksServicesDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/evolution/$instance': {
      id: '/api/public/webhooks/evolution/$instance'
      path: '/$instance'
      fullPath: '/api/public/webhooks/evolution/$instance'
      preLoaderRoute: typeof ApiPublicWebhooksEvolutionInstanceRouteImport
      parentRoute: typeof ApiPublicWebhooksEvolutionRoute
    }
  }
}

interface ApiPublicWebhooksEvolutionRouteChildren {
  ApiPublicWebhooksEvolutionInstanceRoute: typeof ApiPublicWebhooksEvolutionInstanceRoute
}

const ApiPublicWebhooksEvolutionRouteChildren: ApiPublicWebhooksEvolutionRouteChildren =
  {
    ApiPublicWebhooksEvolutionInstanceRoute:
      ApiPublicWebhooksEvolutionInstanceRoute,
  }

const ApiPublicWebhooksEvolutionRouteWithChildren =
  ApiPublicWebhooksEvolutionRoute._addFileChildren(
    ApiPublicWebhooksEvolutionRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoRestritoRoute: AcessoRestritoRoute,
  AdminDnsRotasRoute: AdminDnsRotasRoute,
  AdminPlanosPagamentosRoute: AdminPlanosPagamentosRoute,
  AgendaDisparoRoute: AgendaDisparoRoute,
  AjudaRoute: AjudaRoute,
  AjudaIaRoute: AjudaIaRoute,
  AppsPortalRoute: AppsPortalRoute,
  AuthRoute: AuthRoute,
  BackupRoute: BackupRoute,
  BackupGeralRoute: BackupGeralRoute,
  BaseConhecimentoRoute: BaseConhecimentoRoute,
  BlogRoute: BlogRoute,
  CadastrosServicosRoute: CadastrosServicosRoute,
  CampanhasManuaisRoute: CampanhasManuaisRoute,
  CatalogoServidoresRoute: CatalogoServidoresRoute,
  ClientesRoute: ClientesRoute,
  CobrancaAutomaticaRoute: CobrancaAutomaticaRoute,
  CobrancasRoute: CobrancasRoute,
  ConfiguracaoInicialRoute: ConfiguracaoInicialRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConfiguracoesRevendaRoute: ConfiguracoesRevendaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EmpresasRoute: EmpresasRoute,
  FaqRoute: FaqRoute,
  FilaSimuladaRoute: FilaSimuladaRoute,
  FinanceiroRoute: FinanceiroRoute,
  FuncionalidadesRoute: FuncionalidadesRoute,
  GestaoServicosRoute: GestaoServicosRoute,
  IaRoute: IaRoute,
  IaAtendenteRoute: IaAtendenteRoute,
  IaConfigRoute: IaConfigRoute,
  ImportarClientesRoute: ImportarClientesRoute,
  IndicacoesRoute: IndicacoesRoute,
  LoginRoute: LoginRoute,
  MensagensRoute: MensagensRoute,
  MeusDadosRoute: MeusDadosRoute,
  MigracaoEmpresaRoute: MigracaoEmpresaRoute,
  MinhaAssinaturaRoute: MinhaAssinaturaRoute,
  OperacaoDiaRoute: OperacaoDiaRoute,
  PendenciasRoute: PendenciasRoute,
  PlanosRoute: PlanosRoute,
  PreparacaoBackendRoute: PreparacaoBackendRoute,
  RegrasDisparoRoute: RegrasDisparoRoute,
  RelatorioRoute: RelatorioRoute,
  RenovacoesPaineisRoute: RenovacoesPaineisRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaasPlanosRoute: SaasPlanosRoute,
  SegurancaLocalRoute: SegurancaLocalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestesRoute: TestesRoute,
  TreinarIaRoute: TreinarIaRoute,
  WhatsappRoute: WhatsappRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminVpsRoute: AdminVpsRoute,
  AtendimentoIaTokenRoute: AtendimentoIaTokenRoute,
  PagamentosHistoricoRoute: PagamentosHistoricoRoute,
  PagamentosMercadoPagoRoute: PagamentosMercadoPagoRoute,
  PagarRefRoute: PagarRefRoute,
  ApiPublicHooksServicesDispatchRoute: ApiPublicHooksServicesDispatchRoute,
  ApiPublicHooksSyncCronSecretRoute: ApiPublicHooksSyncCronSecretRoute,
  ApiPublicHooksWaDispatchRoute: ApiPublicHooksWaDispatchRoute,
  ApiPublicMpMarketplaceWebhookRoute: ApiPublicMpMarketplaceWebhookRoute,
  ApiPublicMpOauthCallbackRoute: ApiPublicMpOauthCallbackRoute,
  ApiPublicMpSaasWebhookRoute: ApiPublicMpSaasWebhookRoute,
  ApiPublicWebhooksEvolutionRoute: ApiPublicWebhooksEvolutionRouteWithChildren,
  ApiPublicWebhooksMercadoPagoRoute: ApiPublicWebhooksMercadoPagoRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
