/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestesRouteImport } from './routes/testes'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as RegrasDisparoRouteImport } from './routes/regras-disparo'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as OperacaoDiaRouteImport } from './routes/operacao-dia'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as IndicacoesRouteImport } from './routes/indicacoes'
import { Route as ImportarClientesRouteImport } from './routes/importar-clientes'
import { Route as IaRouteImport } from './routes/ia'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FilaSimuladaRouteImport } from './routes/fila-simulada'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CobrancasRouteImport } from './routes/cobrancas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CatalogoServidoresRouteImport } from './routes/catalogo-servidores'
import { Route as CampanhasManuaisRouteImport } from './routes/campanhas-manuais'
import { Route as BaseConhecimentoRouteImport } from './routes/base-conhecimento'
import { Route as IndexRouteImport } from './routes/index'

const TestesRoute = TestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasDisparoRoute = RegrasDisparoRouteImport.update({
  id: '/regras-disparo',
  path: '/regras-disparo',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoDiaRoute = OperacaoDiaRouteImport.update({
  id: '/operacao-dia',
  path: '/operacao-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacoesRoute = IndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarClientesRoute = ImportarClientesRouteImport.update({
  id: '/importar-clientes',
  path: '/importar-clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaSimuladaRoute = FilaSimuladaRouteImport.update({
  id: '/fila-simulada',
  path: '/fila-simulada',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancasRoute = CobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoServidoresRoute = CatalogoServidoresRouteImport.update({
  id: '/catalogo-servidores',
  path: '/catalogo-servidores',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasManuaisRoute = CampanhasManuaisRouteImport.update({
  id: '/campanhas-manuais',
  path: '/campanhas-manuais',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseConhecimentoRoute = BaseConhecimentoRouteImport.update({
  id: '/base-conhecimento',
  path: '/base-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/campanhas-manuais': typeof CampanhasManuaisRoute
  '/catalogo-servidores': typeof CatalogoServidoresRoute
  '/clientes': typeof ClientesRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/empresas': typeof EmpresasRoute
  '/fila-simulada': typeof FilaSimuladaRoute
  '/financeiro': typeof FinanceiroRoute
  '/ia': typeof IaRoute
  '/importar-clientes': typeof ImportarClientesRoute
  '/indicacoes': typeof IndicacoesRoute
  '/mensagens': typeof MensagensRoute
  '/operacao-dia': typeof OperacaoDiaRoute
  '/pendencias': typeof PendenciasRoute
  '/regras-disparo': typeof RegrasDisparoRoute
  '/relatorio': typeof RelatorioRoute
  '/testes': typeof TestesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/campanhas-manuais': typeof CampanhasManuaisRoute
  '/catalogo-servidores': typeof CatalogoServidoresRoute
  '/clientes': typeof ClientesRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/empresas': typeof EmpresasRoute
  '/fila-simulada': typeof FilaSimuladaRoute
  '/financeiro': typeof FinanceiroRoute
  '/ia': typeof IaRoute
  '/importar-clientes': typeof ImportarClientesRoute
  '/indicacoes': typeof IndicacoesRoute
  '/mensagens': typeof MensagensRoute
  '/operacao-dia': typeof OperacaoDiaRoute
  '/pendencias': typeof PendenciasRoute
  '/regras-disparo': typeof RegrasDisparoRoute
  '/relatorio': typeof RelatorioRoute
  '/testes': typeof TestesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/campanhas-manuais': typeof CampanhasManuaisRoute
  '/catalogo-servidores': typeof CatalogoServidoresRoute
  '/clientes': typeof ClientesRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/empresas': typeof EmpresasRoute
  '/fila-simulada': typeof FilaSimuladaRoute
  '/financeiro': typeof FinanceiroRoute
  '/ia': typeof IaRoute
  '/importar-clientes': typeof ImportarClientesRoute
  '/indicacoes': typeof IndicacoesRoute
  '/mensagens': typeof MensagensRoute
  '/operacao-dia': typeof OperacaoDiaRoute
  '/pendencias': typeof PendenciasRoute
  '/regras-disparo': typeof RegrasDisparoRoute
  '/relatorio': typeof RelatorioRoute
  '/testes': typeof TestesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base-conhecimento'
    | '/campanhas-manuais'
    | '/catalogo-servidores'
    | '/clientes'
    | '/cobrancas'
    | '/configuracoes'
    | '/diagnostico'
    | '/empresas'
    | '/fila-simulada'
    | '/financeiro'
    | '/ia'
    | '/importar-clientes'
    | '/indicacoes'
    | '/mensagens'
    | '/operacao-dia'
    | '/pendencias'
    | '/regras-disparo'
    | '/relatorio'
    | '/testes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base-conhecimento'
    | '/campanhas-manuais'
    | '/catalogo-servidores'
    | '/clientes'
    | '/cobrancas'
    | '/configuracoes'
    | '/diagnostico'
    | '/empresas'
    | '/fila-simulada'
    | '/financeiro'
    | '/ia'
    | '/importar-clientes'
    | '/indicacoes'
    | '/mensagens'
    | '/operacao-dia'
    | '/pendencias'
    | '/regras-disparo'
    | '/relatorio'
    | '/testes'
  id:
    | '__root__'
    | '/'
    | '/base-conhecimento'
    | '/campanhas-manuais'
    | '/catalogo-servidores'
    | '/clientes'
    | '/cobrancas'
    | '/configuracoes'
    | '/diagnostico'
    | '/empresas'
    | '/fila-simulada'
    | '/financeiro'
    | '/ia'
    | '/importar-clientes'
    | '/indicacoes'
    | '/mensagens'
    | '/operacao-dia'
    | '/pendencias'
    | '/regras-disparo'
    | '/relatorio'
    | '/testes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaseConhecimentoRoute: typeof BaseConhecimentoRoute
  CampanhasManuaisRoute: typeof CampanhasManuaisRoute
  CatalogoServidoresRoute: typeof CatalogoServidoresRoute
  ClientesRoute: typeof ClientesRoute
  CobrancasRoute: typeof CobrancasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EmpresasRoute: typeof EmpresasRoute
  FilaSimuladaRoute: typeof FilaSimuladaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  IaRoute: typeof IaRoute
  ImportarClientesRoute: typeof ImportarClientesRoute
  IndicacoesRoute: typeof IndicacoesRoute
  MensagensRoute: typeof MensagensRoute
  OperacaoDiaRoute: typeof OperacaoDiaRoute
  PendenciasRoute: typeof PendenciasRoute
  RegrasDisparoRoute: typeof RegrasDisparoRoute
  RelatorioRoute: typeof RelatorioRoute
  TestesRoute: typeof TestesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testes': {
      id: '/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof TestesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras-disparo': {
      id: '/regras-disparo'
      path: '/regras-disparo'
      fullPath: '/regras-disparo'
      preLoaderRoute: typeof RegrasDisparoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao-dia': {
      id: '/operacao-dia'
      path: '/operacao-dia'
      fullPath: '/operacao-dia'
      preLoaderRoute: typeof OperacaoDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacoes': {
      id: '/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof IndicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-clientes': {
      id: '/importar-clientes'
      path: '/importar-clientes'
      fullPath: '/importar-clientes'
      preLoaderRoute: typeof ImportarClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila-simulada': {
      id: '/fila-simulada'
      path: '/fila-simulada'
      fullPath: '/fila-simulada'
      preLoaderRoute: typeof FilaSimuladaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobrancas': {
      id: '/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof CobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo-servidores': {
      id: '/catalogo-servidores'
      path: '/catalogo-servidores'
      fullPath: '/catalogo-servidores'
      preLoaderRoute: typeof CatalogoServidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas-manuais': {
      id: '/campanhas-manuais'
      path: '/campanhas-manuais'
      fullPath: '/campanhas-manuais'
      preLoaderRoute: typeof CampanhasManuaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-conhecimento': {
      id: '/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof BaseConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaseConhecimentoRoute: BaseConhecimentoRoute,
  CampanhasManuaisRoute: CampanhasManuaisRoute,
  CatalogoServidoresRoute: CatalogoServidoresRoute,
  ClientesRoute: ClientesRoute,
  CobrancasRoute: CobrancasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EmpresasRoute: EmpresasRoute,
  FilaSimuladaRoute: FilaSimuladaRoute,
  FinanceiroRoute: FinanceiroRoute,
  IaRoute: IaRoute,
  ImportarClientesRoute: ImportarClientesRoute,
  IndicacoesRoute: IndicacoesRoute,
  MensagensRoute: MensagensRoute,
  OperacaoDiaRoute: OperacaoDiaRoute,
  PendenciasRoute: PendenciasRoute,
  RegrasDisparoRoute: RegrasDisparoRoute,
  RelatorioRoute: RelatorioRoute,
  TestesRoute: TestesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
