/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as VencimentosRouteImport } from './routes/vencimentos'
import { Route as ServidoresRouteImport } from './routes/servidores'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as CobrancasRouteImport } from './routes/cobrancas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as AplicativosRouteImport } from './routes/aplicativos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminReceitaRouteImport } from './routes/admin/receita'
import { Route as AdminFilasRouteImport } from './routes/admin/filas'
import { Route as AdminFalhasRouteImport } from './routes/admin/falhas'
import { Route as AdminEmpresasRouteImport } from './routes/admin/empresas'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const VencimentosRoute = VencimentosRouteImport.update({
  id: '/vencimentos',
  path: '/vencimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServidoresRoute = ServidoresRouteImport.update({
  id: '/servidores',
  path: '/servidores',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancasRoute = CobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicativosRoute = AplicativosRouteImport.update({
  id: '/aplicativos',
  path: '/aplicativos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReceitaRoute = AdminReceitaRouteImport.update({
  id: '/admin/receita',
  path: '/admin/receita',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFilasRoute = AdminFilasRouteImport.update({
  id: '/admin/filas',
  path: '/admin/filas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFalhasRoute = AdminFalhasRouteImport.update({
  id: '/admin/falhas',
  path: '/admin/falhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/admin/empresas',
  path: '/admin/empresas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aplicativos': typeof AplicativosRoute
  '/assistente': typeof AssistenteRoute
  '/clientes': typeof ClientesRoute
  '/cobrancas': typeof CobrancasRoute
  '/pagamentos': typeof PagamentosRoute
  '/resultados': typeof ResultadosRoute
  '/servidores': typeof ServidoresRoute
  '/vencimentos': typeof VencimentosRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/falhas': typeof AdminFalhasRoute
  '/admin/filas': typeof AdminFilasRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aplicativos': typeof AplicativosRoute
  '/assistente': typeof AssistenteRoute
  '/clientes': typeof ClientesRoute
  '/cobrancas': typeof CobrancasRoute
  '/pagamentos': typeof PagamentosRoute
  '/resultados': typeof ResultadosRoute
  '/servidores': typeof ServidoresRoute
  '/vencimentos': typeof VencimentosRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/falhas': typeof AdminFalhasRoute
  '/admin/filas': typeof AdminFilasRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aplicativos': typeof AplicativosRoute
  '/assistente': typeof AssistenteRoute
  '/clientes': typeof ClientesRoute
  '/cobrancas': typeof CobrancasRoute
  '/pagamentos': typeof PagamentosRoute
  '/resultados': typeof ResultadosRoute
  '/servidores': typeof ServidoresRoute
  '/vencimentos': typeof VencimentosRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/falhas': typeof AdminFalhasRoute
  '/admin/filas': typeof AdminFilasRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aplicativos'
    | '/assistente'
    | '/clientes'
    | '/cobrancas'
    | '/pagamentos'
    | '/resultados'
    | '/servidores'
    | '/vencimentos'
    | '/whatsapp'
    | '/admin/empresas'
    | '/admin/falhas'
    | '/admin/filas'
    | '/admin/receita'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aplicativos'
    | '/assistente'
    | '/clientes'
    | '/cobrancas'
    | '/pagamentos'
    | '/resultados'
    | '/servidores'
    | '/vencimentos'
    | '/whatsapp'
    | '/admin/empresas'
    | '/admin/falhas'
    | '/admin/filas'
    | '/admin/receita'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/aplicativos'
    | '/assistente'
    | '/clientes'
    | '/cobrancas'
    | '/pagamentos'
    | '/resultados'
    | '/servidores'
    | '/vencimentos'
    | '/whatsapp'
    | '/admin/empresas'
    | '/admin/falhas'
    | '/admin/filas'
    | '/admin/receita'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AplicativosRoute: typeof AplicativosRoute
  AssistenteRoute: typeof AssistenteRoute
  ClientesRoute: typeof ClientesRoute
  CobrancasRoute: typeof CobrancasRoute
  PagamentosRoute: typeof PagamentosRoute
  ResultadosRoute: typeof ResultadosRoute
  ServidoresRoute: typeof ServidoresRoute
  VencimentosRoute: typeof VencimentosRoute
  WhatsappRoute: typeof WhatsappRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminFalhasRoute: typeof AdminFalhasRoute
  AdminFilasRoute: typeof AdminFilasRoute
  AdminReceitaRoute: typeof AdminReceitaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vencimentos': {
      id: '/vencimentos'
      path: '/vencimentos'
      fullPath: '/vencimentos'
      preLoaderRoute: typeof VencimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servidores': {
      id: '/servidores'
      path: '/servidores'
      fullPath: '/servidores'
      preLoaderRoute: typeof ServidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobrancas': {
      id: '/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof CobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplicativos': {
      id: '/aplicativos'
      path: '/aplicativos'
      fullPath: '/aplicativos'
      preLoaderRoute: typeof AplicativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/receita': {
      id: '/admin/receita'
      path: '/admin/receita'
      fullPath: '/admin/receita'
      preLoaderRoute: typeof AdminReceitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/filas': {
      id: '/admin/filas'
      path: '/admin/filas'
      fullPath: '/admin/filas'
      preLoaderRoute: typeof AdminFilasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/falhas': {
      id: '/admin/falhas'
      path: '/admin/falhas'
      fullPath: '/admin/falhas'
      preLoaderRoute: typeof AdminFalhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/admin/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AplicativosRoute: AplicativosRoute,
  AssistenteRoute: AssistenteRoute,
  ClientesRoute: ClientesRoute,
  CobrancasRoute: CobrancasRoute,
  PagamentosRoute: PagamentosRoute,
  ResultadosRoute: ResultadosRoute,
  ServidoresRoute: ServidoresRoute,
  VencimentosRoute: VencimentosRoute,
  WhatsappRoute: WhatsappRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminFalhasRoute: AdminFalhasRoute,
  AdminFilasRoute: AdminFilasRoute,
  AdminReceitaRoute: AdminReceitaRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
